= babel-preset-njs
:npm-name: babel-preset-njs
:gh-name: jirutka/{npm-name}
:ci-workflow: npmjs
:babel-doc-uri: https://babeljs.io/docs/en
:object-rest-spread-mdn-uri: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Spread_in_object_literals
:array-spread-mdn-uri: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Spread_in_array_literals
:array-destructuring-mdn-uri: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Array_destructuring

ifdef::env-github[]
image:https://img.shields.io/npm/v/{npm-name}.svg[npm Version, link="https://www.npmjs.org/package/{npm-name}"]
image:https://github.com/{gh-name}/workflows/{ci-workflow}/badge.svg[CI State, link=https://github.com/{gh-name}/actions?query=workflow%3A%22{ci-workflow}%22]
endif::env-github[]

A https://babeljs.io[Babel] https://babeljs.io/docs/en/presets[preset] for transforming JavaScript code with modern language features into code compatible with https://github.com/nginx/njs[njs] (NGINX JavaScript).
This preset includes support for all the ECMAScript features that TypeScript supports (https://tc39.es/process-document/[Stage] 3+).


== Installation

[source, sh, subs="+attributes"]
----
# using npm:
npm install --save-dev {npm-name}
# or using yarn:
yarn add --dev {npm-name}
----


== Usage

=== With a Configuration File (Recommended)

[source, json, subs="+attributes"]
----
{
  "presets": ["{npm-name}"]
}
----

[source, json, subs="+attributes"]
----
{
  "presets": [
    ["{npm-name}", { "assumeArrayIterables": false }]
  ]
}
----


=== Via CLI

[source, sh, subs="+attributes"]
babel --presets {npm-name} script.js


=== Via Node API

[source, js, subs="+attributes"]
----
require('@babel/core').transform('code', {
  presets: [require('{npm-name}')],
})
----


== Options

=== `assumeArrayIterables`
`boolean`, defaults to `true`

Assume that all iterables used in `for...of` loops, {array-spread-mdn-uri}[array spread syntax] and {array-destructuring-mdn-uri}[array destructuring] are arrays.
This produces more compact and significantly more performant code, but it will fail in runtime if the iterable is not an array.

TypeScript transpiler uses the same approach for ES5 target when `downlevelIteration` is disabled.
It also indicates error when the iterable is not an array.

It sets the following plugin options:

* {babel-doc-uri}/babel-plugin-transform-for-of#assumearray[for-of]: `assumeArray`
* {babel-doc-uri}/babel-plugin-transform-spread#loose[spread]: `loose`
* {babel-doc-uri}/babel-plugin-transform-destructuring#loose[destructuring]: `loose`
* {babel-doc-uri}/babel-plugin-proposal-private-property-in-object#loose[private-property-in-object]: `loose`


=== `looseClasses`
`boolean`, defaults to `true`

Define class methods and properties using a simple assignment expression instead of `Object.defineProperty()`.
This produces more compact and performant code, but it might produce unexpected results in some (corner) cases.
TypeScript transpiler uses the same approach.

It sets the following plugin options:

* {babel-doc-uri}/babel-plugin-transform-classes#loose[classes]: `loose`
* {babel-doc-uri}/babel-plugin-proposal-class-properties#loose[class-properties]: `loose`


=== `looseObjectRestSpread`
`boolean`, defaults to `true`

Transform {object-rest-spread-mdn-uri}[object rest/spread properties] using `Object.assign()` instead of Babel’s `objectSpread` helper.
This produces more compact and performant code, but it might produce unexpected results in some (corner) cases (when overwriting read-only target property).
TypeScript transpiler uses the same approach.

It sets the following plugin options:

* {babel-doc-uri}/babel-plugin-proposal-object-rest-spread#loose[object-rest-spread]: `loose`


=== `looseParameters`
`boolean`, defaults to `true`

In loose mode, function parameters with default values will be counted into the arity of the function.
This is not spec behaviour where these parameters do not add to function arity, but it produces more compact and performant code.
TypeScript transpiler uses the same approach.

It sets the following plugin options:

* {babel-doc-uri}/babel-plugin-transform-parameters#loose[parameters]: `loose`


== Included Plugins

This preset includes the following transform plugins:

* {babel-doc-uri}/babel-plugin-proposal-class-properties[class-properties]
* {babel-doc-uri}/babel-plugin-proposal-export-namespace-from[export-namespace-from]
* {babel-doc-uri}/babel-plugin-proposal-logical-assignment-operators[logical-assignment-operators]
* {babel-doc-uri}/babel-plugin-proposal-object-rest-spread[object-rest-spread]
* {babel-doc-uri}/babel-plugin-proposal-optional-catch-binding[optional-catch-binding]
* {babel-doc-uri}/babel-plugin-proposal-optional-chaining[optional-chaining]
* {babel-doc-uri}/babel-plugin-proposal-private-property-in-object[private-property-in-object]
* {babel-doc-uri}/babel-plugin-proposal-unicode-property-regex[unicode-property-regex]
* {babel-doc-uri}/babel-plugin-transform-block-scoping[block-scoping]
* {babel-doc-uri}/babel-plugin-transform-classes[classes]
* {babel-doc-uri}/babel-plugin-transform-destructuring[destructuring]
* {babel-doc-uri}/babel-plugin-transform-dotall-regex[dotall-regex]
* {babel-doc-uri}/babel-plugin-transform-for-of[for-of]
* {babel-doc-uri}/babel-plugin-transform-new-target[new-target]
* {babel-doc-uri}/babel-plugin-transform-object-super[object-super]
* {babel-doc-uri}/babel-plugin-transform-parameters[parameters]
* {babel-doc-uri}/babel-plugin-transform-spread[spread]
* {babel-doc-uri}/babel-plugin-transform-unicode-escapes[unicode-escapes]
* {babel-doc-uri}/babel-plugin-transform-unicode-regex[unicode-regex]
* https://github.com/rpetrich/babel-plugin-transform-async-to-promises[async-to-promises]


== References

* http://nginx.org/en/docs/njs/compatibility.html[njs ECMAScript Compatibility]


== License

This project is licensed under http://opensource.org/licenses/MIT/[MIT License].
